version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 17666:80  # 暴露端口
    volumes: # 挂载
      - /home/Dun/dunblog/nginx/html:/usr/share/nginx/html
      - /home/Dun/dunblog/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  dunblog:
    image: dunblog:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8081:8081
    volumes: # 挂载
      - /home/Dun/dunblog/file/upload/img:/usr/file
