export const Pages = {
    BlogList: 'BlogList',
    BlogDetail: 'BlogDetail',
    Login_Admin:'Login_Admin',
    CategoryList:'CategoryList',
    CategoryDetail:'CategoryDetail',
    Archives:'Archives',
    Admin:'Admin',
    Dashboard:'Dashboard',
    Front:'Front',
    Error:'Error',
    BlogList_Admin:'BlogList_Admin',
    CategoryList_Admin:'CategoryList_Admin',
    BlogEdit_Admin:'BlogEdit_Admin',
    TagList_Admin:'TagList_Admin',
    DiaryList_Admin:'DiaryList_Admin',
    DiaryEdit_Admin:'DiaryEdit_Admin',
    CommentList_Admin:'CommentList_Admin',
    CommentModeration_Admin:'CommentModeration_Admin',
}
